apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wapc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wapc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wapc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wapc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wapc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mmts-tenant/rhtap-demo-app/hacbs-test-project-wapc@sha256:0ce70f492ca07b2728b064c2bad022f8840a4ac04928dbf0295b9797ebe55a22
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
