apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-wapc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mmts-tenant/rhtap-demo-app/hacbs-test-project-wapc@sha256:7922511420f3e8dc900ce18002908b51dfb10c3d70e9859a87519482130cdbfd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
